### ISSUE TITLE
IO Error

### ISSUE THREAD

**Issue by jmscsns** [deadcyclo/narrative-ripper#1]
Trying to run the downloader (in OS X El Capitan) is hitting an error after about twenty photos:

`IOError: ('http error', 403, 'Forbidden', <httplib.HTTPMessage instance at 0x11066e2d8>)`

It appears to be getting stuck on the same picture again and again. When it happens other pictures being downloaded around the same time are being downloaded as zero bytes (and not re-downloaded on subsequent runs)

**Comment by deadcyclo** [comment]
That is really strange. There isn't any kind of authentication going on in the downloader. All of the image urls are public. (Yeah. They do security through obscurity). 

I wonder if you might be hitting some sort of rate limiting. How many threads are you running? Could you try running with only one thread?

To redownload just delete the offending 0-byte files and run again. The app simply checks if a file with the given name exists or not and skips the download if it does.

Finally. Would you be ok with sending me an email with the url to the image that gets 403 forbidden so I can test on my end?

**Comment by jmscsns** [comment]
Yeah, I was a bit surprised to see security through obscurity.

In the light of day (and not trying to run it after a few drinks!) I see my problem was actually not quite what I'd thought. It was actually the penultimate file that was being blocked, not the one immediately before the error. (I'm guessing those last ones were the zero byte files, but deleted them without checking, sorry.)

I'd got around it by creating a dummy file for that image and re-running, and it's been chugging away happily ever since. Happy to send over the link when it's done. 

One other thing in case you are interested, running on a Mac OX X 10.11.6 and Python 2.7.10 I had problems with authenticating ripper.py. These were resolved when I included the apikey, secret (and path) in the code rather than as inputs. I have no idea why that resolved the issue and simply went with it.

**Comment by deadcyclo** [comment]
Great to hear you got it working.

Interesting. I wonder if there is some kind of issue with the newline terminator on mac or if it's a character encoding issue. If I get around to it I'll try to convince somebody to try it on a mac at work on monday ;)

**Comment by deadcyclo** [comment]
I'm going to go ahead and close this issue now. Seems like a lot of people are having issues with narrative having bad quality. Specially pointers to moments that don't exist. I have a feeling they haven't used transactions and roll backs, so probably any kind of error/failure during upload, data add or data delete leaves a corrupt entry in the database.
