### ISSUE TITLE
KeyError: 'g1_webrender'

### ISSUE THREAD

**Issue by juhovii** [deadcyclo/narrative-ripper#11]
Executing "python downloader.py all" results in this kind of error after the script has finished checking for downloaded HD photos:

>  Finding webrender photos 
> Traceback (most recent call last):
>   File "downloader.py", line 220, in <module>
>     get_photos_by_type(pool, path, 'g1_webrender', 'images/webrender/{uuid}', ' Finding webrender photos ', ' Downloading {cnt} webrender photos')
>   File "downloader.py", line 143, in get_photos_by_type
>     files = get_photo_urls(path, type, storagepath)
>   File "downloader.py", line 80, in get_photo_urls
>     photos.append({'url' : image['renders'][type]['url'], 'dir' : os.path.join(path, storage_subpath.format(uuid=image['moment_uuid']))})
> KeyError: 'g1_webrender'

New folders are created though.
Also the terminal window is now colored green until I try executing the same command again.
Meta data and HD photo / video download worked fine.
Running on Ubuntu 14.04.

![downloader_error](https://cloud.githubusercontent.com/assets/4893218/19406994/1702dd78-92cf-11e6-9f89-c96f5204643a.png)

**Comment by deadcyclo** [comment]
@juhovii I just pushed a new version that should handle this types of errors, and simply skip the missing render type. Could you please try it, and let me know if it works for you?

**Comment by juhovii** [comment]
It got past that point and looks promising so far. It is now downloading extra content.

**Comment by juhovii** [comment]
Worked fine.
