### ISSUE TITLE
crash at downloader.py line 114, in get_video_urls

### ISSUE THREAD

**Issue by thederan** [deadcyclo/narrative-ripper#12]
I think when it gets to start to download the videos it crashes with:

`downloader.py line 114, in get_ideo_urls
for f in os.listdirtos.patj.join(path, 'metadata/timeline'`

No such file or directory.

**Comment by deadcyclo** [comment]
hmm... Do you have a file named metadata/timeline/page-1.json?

**Comment by thederan** [comment]
There is no folder /timeline. Only /moment-overview and /moments

**Comment by deadcyclo** [comment]
Then you don't have all of your metadata. You need to run the ripper again.
