### ISSUE TITLE
python_oauth2_token module import

### ISSUE THREAD

**Issue by umamiking** [deadcyclo/narrative-ripper#2]
Windows 10, python 2.7.3

When I try to run `python ripper.py`, I get the following error:

```
Traceback (most recent call last):
  File "ripper.py", line 21, in <module>
    from python_oauth2_token import get_token
  File "C:\Temp\narrative-ripper-master\narrative-ripper-master\python_oauth2_token\__init__.py", line 1, in <module>
    import requests
ImportError: No module named requests
```

**Comment by deadcyclo** [comment]
So. Turns out that he oauth library from narrative requires the [requests python package](https://pypi.python.org/pypi/requests/2.11.1). Install that and you should be good to go. I've updated the readme to reflect this.
