### ISSUE TITLE
requests not installed by default (?)

### ISSUE THREAD

**Issue by dittaeva** [deadcyclo/narrative-ripper#8]
It said somewhere in the Readme to leave a note about missing dependencies: In my Elementary OS (Ubuntu clone distro) where I had python2.6-minimal, and since upgraded to python-full "requests" was not installed.

I don't know which is the easiest way for a newbie to install it. Myself I did `sudo apt-get install pip` and `sudo pip install requests` to solve the problem (after sudo `apt-get install python-full`). I can make a pull request for an amended readme if this looks like an ok way to do it.

**Comment by umamiking** [comment]
I used the same steps and worked fine. I didn't do the `python-full` step and I am not sure it's even related to the `requests` dependencies. It might be confusing to people to add that part in, if `python-full` is not a requirement for `requests`.

**Comment by deadcyclo** [comment]
Thanks @dittaeva I mistakenly removed the information about the need for requests when applying the patch for email/password login. I've added it back now.

@umamiking @dittaeva The readme should list all python packages used that aren't part of python core, but shouldn't give installation instructions as those would vary based on OS, environment and personal preferences.
