### ISSUE TITLE
KeyError: 'access token'

### ISSUE THREAD

**Issue by katsushiro** [deadcyclo/narrative-ripper#9]
Hey, first of all, thanks for making this, the official Narrative client has been hopeless for me. I'm running Windows 10, using Python 2.7.11, made sure to install the requests package and tossed in the colorama package as well. When I try to run the script, it seems to go ok, takes my email, password, and then asks where I want to save the pictures. I point it to a D:\Narrative folder I created, and it immediately fails with the following trace: 

Traceback (most recent call last):
  File "ripper.py", line 108, in <module>
    do_token_stuff(token)
  File "ripper.py", line 80, in do_token_stuff
    print token['access_token']
KeyError: 'access_token'

I've double-checked my password is correct, if I purposefully put in the wrong password it tells me I have an incorrect password before it gets to the part where it asks me to save, so I'm fairly certain that's not the problem. Do you have any suggestions?

**Comment by deadcyclo** [comment]
Hmm... For some reason you aren't getting an access token. If you were on linux I would ask you to run a curl command to see what happens, but I have no idea how you would test a post command on windows unfortunately. If you have access to mac or linux you can try running curl --data "grant_type=password&client_id=ios&email=YOUREMAIL&password=YOURPASSWORD" https://narrativeapp.com/oauth2/token/ (DON'T PASTE THE RESULT HERE, SEND ME A MESSAGE WITH IT). If not you might be able to use a plugin for chrome or firefox that allows you to test post commands.

**Comment by katsushiro** [comment]
Alright, I'll see if I can spin up a quick Linux VM when I get home tonight and try from it, and will let you know the results. Thanks for the reply, and thanks again for creating this.

**Comment by deadcyclo** [comment]
Sure thing. Let me know how it goes

**Comment by katsushiro** [comment]
Hey, just updating here- turns out I had the wrong password after all. I did set up an Ubuntu VM, ran the curl command, got back an "Invalid credentials given" error. Dug around and found an old password, I thought I'd changed it but turns out I never did, old password was still set. Used that one and the script is running correctly, so, we're all good. Thanks again for your assistance! I'll go ahead and close this out.
